[package]
name = "ethereum-bridge-primitives"
version = "0.1.0"
authors = ["Ronyang <yrong1997@gmail.com>"]
edition = "2018"

[dependencies]
enum-iterator = "0.6.0"
codec = { package = "parity-scale-codec", version = "2.3.0", default-features = false, features = ["derive"] }
ethbloom = { version = "0.11.0", default-features = false }
ethereum-types = { version = "0.12.0", default-features = false, features = ["codec", "rlp", "serialize"] }
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }
hex-literal = { version = "0.3.1", default-features = false }
libsecp256k1 = { version = "0.3", default-features = false }
parity-bytes = { version = "0.1.2", default-features = false }
rlp = { version = "0.5", default-features = false }
serde = { version = "1.0.101", optional = true }
serde_derive = { version = "1.0.101", optional = true }
serde-big-array = { version = "0.2", optional = true }
getrandom = { version = "0.2.1", features = ["js"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }
rand = "0.7.3"
serde_json = "1.0"

frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }

ethabi = { git = "https://github.com/snowfork/ethabi-decode.git", package = "ethabi-decode", branch = "master", default-features = false }
ethash = { git = "https://github.com/snowfork/ethash.git", branch = "master", default-features = false }

[dev-dependencies]
wasm-bindgen-test = "0.3.19"


[features]
default = ["std"]
std = [
	"serde",
	"serde_derive",
	"serde-big-array",
	"codec/std",
	"ethabi/std",
	"ethash/std",
	"ethbloom/std",
	"ethereum-types/std",
	"hex/std",
	"libsecp256k1/std",
	"parity-bytes/std",
	"rlp/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"scale-info/std",
]
